name: leap
description: An opinionated toolkit for creating 2D platformers on top of Flame engine.
version: 0.5.3
homepage: https://github.com/kurtome/leap

environment:
  sdk: ^3.8.1

dependencies:
  flame: ^1.11.0
  flame_behaviors: ^1.0.0
  flame_tiled: ^1.18.0
  flutter:
    sdk: flutter
  tiled: ^0.10.1

dev_dependencies:
  # flame_lint: ^1.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
