include: package:flutter_lints/flutter.yaml

formatter: 
  trailing_commas: preserve

linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude:
    - lib/firebase_options_dev.dart
    - lib/firebase_options_prod.dart
